"""Deterministic OpenAPI 3.1 export for the AIEOS HTTP foundation."""

from __future__ import annotations

import json
from typing import Any

from fastapi import FastAPI
from fastapi.openapi.utils import get_openapi

from aieos.platform.api.problems import ProblemDetails, ProblemErrorItem

_ERROR_STATUSES = ("400", "401", "403", "404", "405", "409", "422", "500", "503")

_CORRELATION_PARAM = {
    "name": "X-AIEOS-Correlation-ID",
    "in": "header",
    "required": False,
    "schema": {"type": "string", "format": "uuid"},
    "description": (
        "Optional correlation identifier. Malformed values are rejected. "
        "The server generates a UUIDv7 when absent. Distinct from request_id."
    ),
}

_CONTEXT_HEADERS = {
    "X-AIEOS-Request-ID": {
        "description": "Server-generated UUIDv7 request identifier. Callers cannot choose it.",
        "schema": {"type": "string", "format": "uuid"},
    },
    "X-AIEOS-Correlation-ID": {
        "description": "Correlation identifier preserved or generated by the server.",
        "schema": {"type": "string", "format": "uuid"},
    },
}


def build_openapi(app: FastAPI) -> dict[str, Any]:
    schema = get_openapi(
        title=app.title,
        version=app.version,
        openapi_version="3.1.0",
        description=app.description,
        routes=app.routes,
    )
    schema["openapi"] = "3.1.0"
    components = schema.setdefault("components", {})
    schemas = components.setdefault("schemas", {})
    schemas.pop("HTTPValidationError", None)
    schemas.pop("ValidationError", None)
    schemas["ProblemDetails"] = ProblemDetails.model_json_schema(
        ref_template="#/components/schemas/{model}"
    )
    schemas["ProblemErrorItem"] = ProblemErrorItem.model_json_schema(
        ref_template="#/components/schemas/{model}"
    )
    problem_content = {
        "application/problem+json": {
            "schema": {"$ref": "#/components/schemas/ProblemDetails"}
        }
    }
    for path_item in schema.get("paths", {}).values():
        if not isinstance(path_item, dict):
            continue
        for method, operation in list(path_item.items()):
            if method.startswith("x-") or not isinstance(operation, dict):
                continue
            params = operation.setdefault("parameters", [])
            if not any(
                p.get("name") == "X-AIEOS-Correlation-ID" and p.get("in") == "header"
                for p in params
                if isinstance(p, dict)
            ):
                params.append(_CORRELATION_PARAM)
            responses = operation.setdefault("responses", {})
            operation_id = operation.get("operationId")
            for status, response in list(responses.items()):
                if not isinstance(response, dict):
                    continue
                headers = response.setdefault("headers", {})
                headers.update(_CONTEXT_HEADERS)
                if status in {"200", "201"} and operation_id in {
                    "content_create",
                    "content_get",
                }:
                    headers["ETag"] = {
                        "description": "Opaque aggregate revision validator",
                        "schema": {"type": "string"},
                    }
                if status == "201" and operation_id == "content_create":
                    headers["Location"] = {
                        "description": "Canonical Content URL",
                        "schema": {"type": "string"},
                    }
                if status in _ERROR_STATUSES:
                    response["content"] = problem_content
            for status in _ERROR_STATUSES:
                responses.setdefault(
                    status,
                    {
                        "description": "RFC 9457 Problem Details",
                        "headers": dict(_CONTEXT_HEADERS),
                        "content": problem_content,
                    },
                )
    return schema


def canonical_openapi_json(schema: dict[str, Any]) -> str:
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"
