"""Deterministic OpenAPI 3.1 export for the AIEOS HTTP foundation."""

from __future__ import annotations

import json
from typing import Any

from fastapi import FastAPI
from fastapi.openapi.utils import get_openapi

from aieos.platform.api.problems import ProblemDetails, ProblemErrorItem

_SUCCESS_STATUSES = {"200", "201"}

_MUTATION_IDEMPOTENCY_IDS = {
    "content_create",
    "content_version_append",
    "content_review_submit",
    "content_review_approve",
    "content_review_request_changes",
    "content_review_reject",
    "content_publish",
    "teaching_work_create",
    "teaching_work_refine",
    "teaching_work_generate",
    "teaching_work_prepare",
}
_IF_MATCH_OPERATION_IDS = {
    "content_version_append",
    "content_review_submit",
    "content_review_approve",
    "content_review_request_changes",
    "content_review_reject",
    "content_publish",
    "teaching_work_refine",
    "teaching_work_generate",
    "teaching_work_prepare",
}
_GET_OPERATION_IDS = {
    "content_get",
    "content_list",
    "content_version_get",
    "teacher_os_review_queue_list",
    "teacher_os_review_queue_get",
    "teaching_work_get",
    "teaching_work_list",
    "teacher_os_today_mission",
    "teaching_work_artifacts_list",
}

_IDEMPOTENCY_PARAM = {
    "name": "Idempotency-Key",
    "in": "header",
    "required": True,
    "schema": {"type": "string", "maxLength": 255},
    "description": "Required retry key. Bounded, not stored in PostgreSQL.",
}

_IF_MATCH_PARAM = {
    "name": "If-Match",
    "in": "header",
    "required": True,
    "schema": {"type": "string"},
    "description": "Required strong aggregate revision validator, e.g. \"r0\".",
}

_CORRELATION_PARAM = {
    "name": "X-AIEOS-Correlation-ID",
    "in": "header",
    "required": False,
    "schema": {"type": "string", "format": "uuid"},
    "description": (
        "Optional correlation identifier. Malformed values are rejected. "
        "The server generates a UUIDv7 when absent. Distinct from request_id."
    ),
}

_CONTEXT_HEADERS = {
    "X-AIEOS-Request-ID": {
        "description": "Server-generated UUIDv7 request identifier. Callers cannot choose it.",
        "schema": {"type": "string", "format": "uuid"},
    },
    "X-AIEOS-Correlation-ID": {
        "description": "Correlation identifier preserved or generated by the server.",
        "schema": {"type": "string", "format": "uuid"},
    },
}


def build_openapi(app: FastAPI) -> dict[str, Any]:
    schema = get_openapi(
        title=app.title,
        version=app.version,
        openapi_version="3.1.0",
        description=app.description,
        routes=app.routes,
    )
    schema["openapi"] = "3.1.0"
    components = schema.setdefault("components", {})
    schemas = components.setdefault("schemas", {})
    schemas.pop("HTTPValidationError", None)
    schemas.pop("ValidationError", None)
    schemas["ProblemDetails"] = ProblemDetails.model_json_schema(
        ref_template="#/components/schemas/{model}"
    )
    schemas["ProblemErrorItem"] = ProblemErrorItem.model_json_schema(
        ref_template="#/components/schemas/{model}"
    )
    # ADR-AIEOS-030 authorized additive Bearer security contract (not OAuth login).
    security_schemes = components.setdefault("securitySchemes", {})
    security_schemes["AIEOSBearerAuth"] = {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": (
            "ADR-AIEOS-030 JWT access token (RS256). Authentication of principal "
            "identity only; not tenant authority or capability authorization."
        ),
    }
    schema["security"] = [{"AIEOSBearerAuth": []}]
    problem_content = {
        "application/problem+json": {
            "schema": {"$ref": "#/components/schemas/ProblemDetails"}
        }
    }
    for path_item in schema.get("paths", {}).values():
        if not isinstance(path_item, dict):
            continue
        for method, operation in list(path_item.items()):
            if method.startswith("x-") or not isinstance(operation, dict):
                continue
            operation["security"] = [{"AIEOSBearerAuth": []}]
            params = operation.setdefault("parameters", [])
            if not any(
                p.get("name") == "X-AIEOS-Correlation-ID" and p.get("in") == "header"
                for p in params
                if isinstance(p, dict)
            ):
                params.append(_CORRELATION_PARAM)
            responses = operation.setdefault("responses", {})
            operation_id = operation.get("operationId")
            if operation_id in _MUTATION_IDEMPOTENCY_IDS:
                _ensure_header_param(params, _IDEMPOTENCY_PARAM)
            if operation_id in _IF_MATCH_OPERATION_IDS:
                _ensure_header_param(params, _IF_MATCH_PARAM)
            if operation_id in _GET_OPERATION_IDS:
                params[:] = [
                    p
                    for p in params
                    if not (
                        isinstance(p, dict)
                        and p.get("in") == "header"
                        and p.get("name") in {"If-Match", "Idempotency-Key"}
                    )
                ]
            for status, response in list(responses.items()):
                if not isinstance(response, dict):
                    continue
                headers = response.setdefault("headers", {})
                headers.update(_CONTEXT_HEADERS)
                if status in {"200", "201"} and operation_id in {
                    "content_create",
                    "content_get",
                    "content_version_append",
                    "content_review_submit",
                    "content_review_approve",
                    "content_review_request_changes",
                    "content_review_reject",
                    "teaching_work_create",
                    "teaching_work_get",
                    "teaching_work_refine",
                }:
                    headers["ETag"] = {
                        "description": "Opaque aggregate revision validator",
                        "schema": {"type": "string"},
                    }
                if status == "201" and operation_id == "content_create":
                    headers["Location"] = {
                        "description": "Canonical Content URL",
                        "schema": {"type": "string"},
                    }
                if status == "201" and operation_id == "teaching_work_create":
                    headers["Location"] = {
                        "description": "Canonical Teaching Work URL",
                        "schema": {"type": "string"},
                    }
                if status == "201" and operation_id == "content_version_append":
                    headers["Location"] = {
                        "description": "Canonical ContentVersion URL",
                        "schema": {"type": "string"},
                    }
                if status not in _SUCCESS_STATUSES:
                    response["content"] = problem_content
    return schema


def _ensure_header_param(params: list, spec: dict[str, Any]) -> None:
    for existing in params:
        if (
            isinstance(existing, dict)
            and existing.get("name") == spec["name"]
            and existing.get("in") == "header"
        ):
            existing["required"] = True
            existing.setdefault("description", spec.get("description"))
            return
    params.append(spec)


def canonical_openapi_json(schema: dict[str, Any]) -> str:
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"
